theme: jekyll-theme-slate

title: Oliver & Co(de)
description: a dev, his diary, and code
logo: oliverandcode-logo.png
show_downloads: false
url: https://oliverandcode.github.io/

# nav links
# if external add external: true
links:
  - title: home
    url: /
    external: false
    # icon: home
  - title: blog
    url: /blog
  - title: projects
    url: /projects
  - title: about
    url: /about

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Oliver Ayers"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
